# 05-1. Q table

In [15]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

In [23]:
env = gym.make('FrozenLake-v1')

In [33]:
Q = np.zeros([env.observation_space.n,env.action_space.n])

lr = .8
y = .95
num_episodes = 2000

rList = []
for i in range(num_episodes):

    s = env.reset()
    rAll = 0
    d = False
    j = 0

    while j < 99:
        j+=1

        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))

        s1,r,d,_ = env.step(a)

        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break

    rList.append(rAll)

In [34]:
print("Score over time: " + str(sum(rList) / num_episodes))

Score over time: 0.4515


In [36]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[1.98888526e-01 3.69880186e-03 3.14228988e-03 4.87821304e-03]
 [1.08817165e-03 8.12421098e-04 2.60666338e-03 4.07098415e-03]
 [1.11611627e-03 2.72139781e-03 3.38485178e-03 1.56066145e-03]
 [1.93019654e-03 3.81648844e-04 3.63625077e-04 4.79166222e-03]
 [8.95590242e-02 3.88384873e-04 1.56427072e-03 2.96356725e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.19515216e-03 2.68021103e-05 3.01609400e-04 1.31093473e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.94903452e-03 9.95963183e-04 4.15356652e-01]
 [1.74072025e-03 2.09314611e-01 0.00000000e+00 0.00000000e+00]
 [1.52860668e-03 2.72510900e-02 2.14648581e-04 3.58665218e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.10829213e-03 0.00000000e+00 6.86023139e-01 1.45827912e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.77498453e-01]
 [0.00000000e+00 0.00000000e+00 0.

In [39]:
Q[0,:]

array([0.19888853, 0.0036988 , 0.00314229, 0.00487821])

In [40]:
Q

array([[1.98888526e-01, 3.69880186e-03, 3.14228988e-03, 4.87821304e-03],
       [1.08817165e-03, 8.12421098e-04, 2.60666338e-03, 4.07098415e-03],
       [1.11611627e-03, 2.72139781e-03, 3.38485178e-03, 1.56066145e-03],
       [1.93019654e-03, 3.81648844e-04, 3.63625077e-04, 4.79166222e-03],
       [8.95590242e-02, 3.88384873e-04, 1.56427072e-03, 2.96356725e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.19515216e-03, 2.68021103e-05, 3.01609400e-04, 1.31093473e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.94903452e-03, 9.95963183e-04, 4.15356652e-01],
       [1.74072025e-03, 2.09314611e-01, 0.00000000e+00, 0.00000000e+00],
       [1.52860668e-03, 2.72510900e-02, 2.14648581e-04, 3.58665218e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.10829213e-03, 0.00000000e+00, 6.86023139e

In [44]:
a = np.random.randn(1,4)

In [45]:
print(a)
print(a*(1/2))

[[ 1.59538742  0.2291119   0.16710508 -0.09120291]]
[[ 0.79769371  0.11455595  0.08355254 -0.04560146]]


In [47]:
np.argmax(Q[s,:] + a*(1/4))

0