In [1]:
import numpy as np
import tensorflow as tf

In [4]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[3,2,1],[6,5,4],[9,8,7]],[[1,1,1],[2,2,2],[3,3,3]]])

In [25]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])

In [26]:
a.reshape(-1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [3, 2, 1, 6, 5, 4, 9, 8, 7],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [27]:
a.reshape(-1,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])

In [35]:
a.reshape(-1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [3, 2, 1, 6, 5, 4, 9, 8, 7],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [36]:
a.reshape(-1,27)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 1, 6, 5, 4, 9, 8, 7, 1, 1, 1, 2,
        2, 2, 3, 3, 3]])

In [38]:
tf.split(a,3,1)

[<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
 array([[[1, 2, 3]],
 
        [[3, 2, 1]],
 
        [[1, 1, 1]]])>,
 <tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
 array([[[4, 5, 6]],
 
        [[6, 5, 4]],
 
        [[2, 2, 2]]])>,
 <tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
 array([[[7, 8, 9]],
 
        [[9, 8, 7]],
 
        [[3, 3, 3]]])>]

In [43]:
27//2

13

In [49]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.random_normal([13,4])

In [6]:
a = np.array([[1,2,3],[2,3,4],[5,6,7]])
k1 = tf.reduce_mean(a,axis=1, keep_dims=True)

In [52]:
print(k1)

Tensor("Mean_1:0", shape=(3, 1), dtype=int32)


In [53]:
k1

<tf.Tensor 'Mean_1:0' shape=(3, 1) dtype=int32>

In [54]:
k2 = tf.reduce_mean(a,axis=1, keep_dims=False)

In [55]:
k2

<tf.Tensor 'Mean_2:0' shape=(3,) dtype=int32>

In [57]:
k1.reshape([-1])

AttributeError: 'Tensor' object has no attribute 'reshape'

In [7]:
tf.gather(tf.reshape(a,[-1]), k1)

<tf.Tensor 'GatherV2:0' shape=(3, 1) dtype=int32>

In [8]:
a.reshape([-1])

array([1, 2, 3, 2, 3, 4, 5, 6, 7])

In [9]:
k1

<tf.Tensor 'Mean:0' shape=(3, 1) dtype=int32>

In [7]:
tf.print(tf.multiply([0,3,4,2,1], [[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]]))

<tf.Operation 'PrintV2' type=PrintV2>

In [11]:
with tf.compat.v1.Session() as sess :
    print(tf.reduce_sum(tf.multiply([0,3,4,2,1], [[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]]), axis = 1).eval())

[0 3 4 2 1]
